### PR TITLE
ISSUE-13 - Fix timezone warning upon successful Sitemap creation and save

### PR DESCRIPTION
**Pull request by sigee**

### CODE REVIEW

**Comment by lewismc** [comment]
Thank you @sigee I will look at this tomorrow

**Review by lewismc — COMMENTED** [review]
Hi @sigee i think this looks great. 
Locally when I test it however, it does not seem to be picking up my PST datetime. It still defaults to UTC. I can verify this by generating a Sitemap... the time here was 09:54PST however the Sitemap time generated is displayed as 2017-06-02T16:54:08+00:00

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9.xsd">
<!-- Created by Sitepod version 1.5.3 - For more information see https://github.com/nasa/sitepod -->
<!-- Last update of sitemap 2017-06-02T16:54:08+00:00 -->
```

**Comment by sigee** [comment]
Hi @lewismc,
It is because when you use it locally, your IP address is 127.0.0.1 (localhost).
I mean $_SERVER['REMOTE_ADDR'] is not the IP address you are using on the internet.
It is just a guess, but maybe it helps if you try to open your local server trough internet.
See: https://whatismyipaddress.com/ and try to open your server on that ip address.
If it is still wrong, you need to upload it to a remote server.
I'm not sure why REMOTE_ADDR is wrong on localhost, but it is. I don't know any solution to fix this (maybe apache) issue.

**Comment by lewismc** [comment]
Got it @sigee thank you

**Pull request merged**
