### PR TITLE
ISSUE-27 Fix licensing headers

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses #27

### CODE REVIEW

**Comment by sigee** [comment]
It is fine. :+1: 
Just a mention:
What do you think about [phpDoc @license](https://phpdoc.org/docs/latest/references/phpdoc/tags/license.html)?

**Comment by lewismc** [comment]
@sigee I like phpDoc much better. I am closing this issue and we can implement the build and documentation using the notation from phpDoc.
Do you know if we can tie it in to the CI process... something like readthedocs.io?

**Comment by sigee** [comment]
@lewismc, I've never used that service.
I know composer can run scripts after install command for example. [https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-](https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-)
If we add [phpdocumentor/phpdocumentor](https://packagist.org/packages/phpdocumentor/phpdocumentor) to the dependencies, we can call it after composer commands.
It is a basic solution, so maybe readthedocs.io is a better one, but I don't know it yet.

**Comment by lewismc** [comment]
I just found the following article @sigee https://blog.cloudobjects.io/coding/opensource/2017/05/19/php-sdk-documentation/
I think this is what we could set up!

**Pull request merged**
